LONG_SUMMARIZE_PROMPT_TMPL=( 
    "You will be given text from new federal regulation. "
    "Your task is to write a detailed summary of the given text, and highlight all main points. "
    "Ensure the following guidelines are met:\n"
    "1. Be verbose in your summary, ensuring that you capture all the essential details, requirements, values, exceptions, and explicit definitions.\n"
    "2. Be sure to mention any alternative approaches that were mentioned or explored, but not adopted.\n"
    "3. Use precise numerical values, not estimates, approximations, or rounding.\n"
    "{compliance_guidance}\n"
    "{additional_guidance}\n"
    "\n"
    "SUMMARY:\n"
)
SHORT_SUMMARIZE_PROMPT_TMPL=(
    "You will be given text from new federal regulation. "
    "Your task is to write a summary of the given section, highlighting all key ideas. "
    "Be precise and brief in your summary, ensuring that you capture all the essential details, requirements, values, exceptions, and explicit definitions. "
    "Do not estimate numerical values or provide your own interpretations. "
    "The summary must be objective, stating only the facts, even if the content is attempting to be persuasive. "
    "\n"
    "{compliance_guidance}\n"
    "{additional_guidance}\n"
    "\n"
    'SUMMARY:\n'
)

FORMAT_SUMMARY_OUTPUT_PROMPT_TMPL=(
    "Please convert this summary into a professional narrative in paragraph format. "
    "Remove any redundant information. "
    "Remove all Markdown formatting, bullet points, and numbered lists. "
    "Maintain the key information but present it in a more formal, report-style format with proper sentence structure and paragraph breaks where appropriate.\n"
    "The summary must be objective, stating only the facts, even if the content is attempting to be persuasive. "
    "\n"
    "For example, transform this:\n"
    "# Main Points\n"
    "- First item\n"
    "- Second item\n"
    "1. Sub point A\n"
    "2. Sub point B\n"
    "\n"
    "Into something like this:\n"
    "The analysis revealed several key findings. First, [content of first item]. "
    "Additionally, [content of second item]. "
    "Within these areas, two important aspects emerged: [sub point A] and [sub point B].\n"
    "\n"
    "SUMMARY:\n"
    "{summary_output}\n"
    "\n"
    "MARKDOWN REMOVED AND PROFESSIONAL NARRATIVE:\n"
)

REFINE_SUMMARIES_PROMPT_TMPL = ("You will be given text containing several independent reports. "
                                "Each report begins with 'Response' and ends with '---------------------'. "
                                "Your task is to rewrite all the responses (i.e. do not summarize) to form a coherent and accurate report. "
                                "Ensure the following guidelines are met:\n"
                                "1. Preserve all of the details in the original report, while ensuring that the final rewrite has a clear narrative flow and logical structure.\n"
                                "2. Remove any redundant information and redundant phrasing (e.g. 'The regulation specifies', 'In summary', 'The text outlines').\n"
                                "3. The summary must be objective, stating only the facts, even if the content is attempting to be persuasive.\n"
                                "\n"
                                "ORIGINAL REPORT:\n"
                                "{summaries}\n"
                                "\n"
                                "REFINED REPORT:\n"
                        )

BULLET_POINTS_PROMPT_TMPL = ("Below is a summary. "
"Your task is to produce a list of bullet points, highlighting all major key points. "
"Be very concise in your bullet points, ensuring that you capture all the high level details. "
"Ensure the following guidelines are met:\n"
"1. The bullet points are objective, stating only the facts, even if the content is attempting to be persuasive.\n"
"2. Use precise numerical values, not estimates, approximations, or rounding.\n"
"3. Do not use Markdown formatting or section titles.\n"
"4. Only return the bullet points. Do not include any additional information or context.\n"
"{compliance_guidance}\n"
"{additional_guidance}\n"
"\n"
"SUMMARY FOR BULLET POINTS:\n"
"{section_str}\n"
"\n"
"BULLET POINTS OF KEY POINTS:\n"
)

GUIDING_PRINCIPLES_BULLET_POINTS_PROMPT_TMPL = ("Below is a section of a newly proposed federal regulation, and a document of a financial firm's guiding principles document. "
"The guiding principles for advocacy were developed to facilitate decisions about which issues the firm should dedicate advocacy resources. "
"Your task is to produce a list of bullet points that highlight which issues (if any) the firm should dedicate advocacy resources to according to their guiding principles document. "
"Be very concise in your bullet points. "
"Provide the guiding principles section reference at the end of each bullet point (e.g. Guiding Principles 2.a.i.1, Guiding Principles 6.c, Guiding Principles 1.d.iii). "
"Do not use Markdown formatting or section titles. "
"Only return the bullet points. If the guiding principles document is not relevant to the section, just return 'Not Relevant'.\n"
"\n"
"SECTION FOR BULLET POINTS:\n"
"{section_str}\n"
"\n"
"GUIDING PRINCIPLES DOCUMENT:\n"
"{guiding_principles}\n"
"\n"
"BULLET POINTS OF KEY POINTS:\n"
)

BULLET_POINT_FACT_CHECKING_PROMPT_TMPL = ("Below are bullet points that need to be fact-checked. "
"ONLY use the information in the context below to determine if each bullet point is correct or false. "
"Verify all numeric values, numeric values in word form, and other factual information to ensure accuracy. "
"Do not use any pre-existing knowledge.\n"
"If a bullet point false, rewrite the bullet point with the correct information, and output in this format:\n"
"- Original bullet point: [Incorrect information]\n"
"- Corrected bullet point: [Corrected information]\n"
"- Supporting Context: [Section context only]\n"
"If all bullet points are true, return 'None'. "
"Only return the bullet points that are false. Do not include any pre-text or post-text.\n"
"\n"
"CONTEXT:\n"
"{section_str}\n"
"\n"
"BULLET POINTS TO FACT-CHECK:\n"
"{statement}\n"
"\n"
"FACT-CHECKING RESPONSE:\n"
)

BULLET_POINT_UPDATE_PROMPT_TMPL = ("Below is a list of bullet points. Some of them are factually incorrect. "
"Your task is to rewrite the incorrect bullet points with the correct information provided in the context below. "
"If a bullet point is correct, leave it as is. "
"If a bullet point is incorrect, rewrite in the format of the original bullet points. "
"Only return the rewritten bullet points. Do not include any pre-text or post-text.\n"
"\n"
"FACTUALLY INCORRECT BULLET POINTS:\n"
"{incorrect_bullet_points}\n"
"\n"
"CORRECTED BULLET POINTS:\n"
"{corrected_bullet_points}\n"
"\n"
"REWRITTEN BULLET POINTS:\n"
)

####################################################################
########################## No longer used ##########################
####################################################################
# TODO: get better prompt
GLOBAL_PRAXIS_SUMMARIZE_PROMPT_TMPL = (
    "You are tasked with refining the summary of a specific section of a proposed federal regulation. "
    "The initial summary was written in isolation, without considering the broader context of the regulation. "
    "Your job is to incorporate relevant global information from the other sections while maintaining the integrity and clarity of the local summary. "
    "Ensure that the rewritten summary integrates key themes, relationships, or overarching points from the other sections where applicable."
    "Do not use any Markdown formatting or bullet points in your response.\n"
    "\n"
    "Local Section Summary:\n"
    "{context_str}\n"
    "\n"
    "\n"
    "Other Section Summaries:\n"
    "{all_other_section_summaries}\n"
    "\n"
    "\n"
    "REWRITE LOCAL SUMMARY WITH INTEGRATED GLOBAL CONTEXT:\n"
    '"""\n'
)

GLOBAL_PRAXIS_QA_PROMPT_TMPL = (
    "You are tasked with comparing the refined summary with the original summary of a specific section of a proposed federal regulation. "
    "The initial summary was written in isolation, without considering the broader context of the regulation. "
    "Your job is to check that the refined summary does not contradict the original summary. "
    "If there are any contradictions, return 'Yes'. Otherwise, return 'No'. "
    "Only return one word, 'Yes' or 'No'. "
    "Do not use any Markdown formatting or bullet points in your response.\n"
    "\n"
    "Original Summary:\n"
    "{context_str}\n"
    "\n"
    "\n"
    "Refined Summary:\n"
    "{refined_summary}\n"
    "\n"
    "\n"
    "DOES THE REFINED SUMMARY CONTRADICT THE ORIGINAL SUMMARY?\n"
    '"""\n'
)

# TODO: finish refining this prompt
REQUEST_FOR_COMMENT_PRAXIS_SUMMARIZE_PROMPT_TMPL = (
    "You are tasked with refining the summary of a specific section of a proposed federal regulation. "
    "The initial summary was written in isolation, without considering the request for comments section. "
    "Your job is add a section to the summary that details information from the original section that might "
    "be relevant to any and all of the questions in the request for comments section. "
    "Ensure that the added section integrates key themes, relationships, or overarching points from the "
    "request for comments section where applicable. "
    "Do not use any Markdown formatting or bullet points in your response.\n"
    "\n"
    "Local Section Summary:\n"
    "{context_str}\n"
    "\n"
    "\n"
    "Request For Comments Section:\n"
    "{request_for_comments_section}\n"
    "\n"
    "\n"
    "INCLUDE SECTION FOR INFORMATION THAT RELATES TO THE REQUEST FOR COMMENTS SECTION:\n"
    '"""\n'
)